publishDir   = "docs/"
baseurl      = "https://mckade.github.io"
title        = "McKade's Homepage"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
Copyright = "Â© McKade Umbenhower 2021"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "A collection of McKade's thoughts and things. This site serves as a dumping ground for my interests, projects, thoughts, tools, techniques, etc. Most of my work revolves around reverse engineering, vulnerability research, IoT development, and systems security."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "McKade's homepage"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "McKade Umbenhower"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd ~/mckade_home"
      logoHomeLink = "/"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact"

  [[menu.main]]
    identifier = "thoughts"
    name       = "Thoughts"
    url        = "/thoughts"

  [[menu.main]]
    identifier = "things"
    name       = "Things"
    url        = "/things"

  [[params.social]]
    name = "github"
    url = "https://github.com/mckade"
